export const sinossi = "Nell'anno 2029, i progressi nella tecnologia cibernetica hanno permesso alle persone di sostituire parti del corpo e organi con quelli robotici. Anche il cervello può essere sostituito con un cyber-brain, con la possibilità, tramite esso, di accedere a Internet e reti diverse. Il maggiore Motoko Kusanagi, un agente cyborg che lavora per il governo, e il suo team hanno ricevuto l'incarico di rintracciare il famigerato hacker noto come \"Il burattinaio\" e scoprire i suoi piani."

export const info = "“Ghost in the Shell” (攻殻機動隊 - Kōkaku kidōtai) è un film d'animazione del 1995 diretto da <span>Mamoru Oshii</span>. Il soggetto è basato sul manga originale omonimo di <span>Masamune Shirow</span>. Prodotto in Giappone dallo studio <span>Production I.G.</span>, il film ha avuto un seguito nel 2004 intitolato “Ghost in the Shell 2 - Innocence” (イノセンス - Inosensu). Nel 2008 la pellicola originale è stata sottoposta ad un profondo restyling, con largo uso della computer grafica, e ripubblicata con il titolo “Ghost in the Shell 2.0”."

export const description = "“Ghost in the Shell” è un anime cyberpunk del 1995 diretto da Mamoru Oshii. Il film è basato sul manga omonimo di Masamune Shirow ed è stato sceneggiato da Kazunori Itō. Il film è una co-produzione internazionale giapponese-britannica, prodotta da Kodansha, Bandai Visual e Manga Entertainment, con le animazioni dello studio Production I.G. Il film è ambientato nel Giappone del 2029 e segue le vicende di Motoko Kusanagi, un agente cyborg di sicurezza pubblica, nella sua caccia a un misterioso hacker conosciuto come \"Il Burattinaio\". La narrazione incorpora temi filosofici incentrati sull'identità di sé in un mondo tecnologicamente avanzato. La musica, composta da Kenji Kawai, include voci in lingua giapponese classica. La critica ha elogiato in particolare la narrazione del film, la colonna sonora e le immagini, ottenute attraverso una combinazione di animazione tradizionale e animazione CGI. Il film, che aveva un budget di oltre 10 milioni di dollari, fu inizialmente un fallimento al botteghino, prima di attirare un seguito di culto in home video."

export const regia1 = '"Il mio intuito mi suggerì che questa storia, di un mondo futuristico, poteva portare un messaggio immediato per il nostro mondo attuale. Sono sempre stato interessato anche ai computer, per la mia esperienza personale con essi. Ho pensato che sarebbe stato interessante fare un film che si svolgesse nel prossimo futuro. Ci sono solo pochi film, anche fuori da Hollywood, che ritraggono chiaramente l\'influenza e il potere dei computer. Ho pensato che questo tema sarebbe stato trasmesso più efficacemente attraverso l\'animazione". Così il regista Mamoru Oshii parla della sua ispirazione per dirigere "Ghost in the Shell", notando inoltre che la tecnologia cambia le persone, ed è diventata parte della cultura del Giappone. Oshii ha dichiarato che il suo approccio alla regia è in diretto contrasto con quella che percepisce essere la formula di Hollywood. Considera cioè le immagini l\'aspetto più importante, seguite dalla storia e solo per ultimi i personaggi. Il film segue lo schema e i punti cardine tipici dello stile narrativo del regista. Si apre con una sequenza d\'azione. In seguito, il film segue un ritmo molto più lento, nel quale lo sviluppo dei personaggi la fa da padrone. Tuttavia il film è punteggiato da diverse sequenze di azione frenetica e veloce.'

export const regia2 = 'Oshii inserisce anche frequentemente una sequenza di montaggio in ciascuno dei suoi film, tipicamente della durata di due minuti, priva di dialogo e ambientata sullo sfondo della musica di Kenji Kawai. Le immagini ricorrenti includono riflessi/specchi, stormi di uccelli e bassotti simili al suo. Il bassotto è stato visto soprattutto in Ghost in the Shell e Innocence. Oshii è particolarmente noto per come si allontana significativamente dal materiale di partenza su cui sono basati i suoi film, come nel suo adattamento di "Ghost in the Shell". Adattando l’opera, il regista ha creato un\'atmosfera più lenta e cupa del manga originale, nella quale è stato escluso completamente l\'umorismo e le battute dei personaggi della storia originale di Masamune Shirow. È noto che le sorelle Wachowski rimasero talmente impressionate da “Ghost in the Shell” al punto da proiettarlo ai loro produttori per mostrargli che tipo di film volevano realizzare per “The Matrix”. Infatti, varie scene di "Ghost in the Shell" sono state apparentemente trasposte nel film. James Cameron è un altro regista che ha espresso la sua ammirazione per Oshii, elogiando “Ghost in the Shell” e affermando che è stato "il primo film d\'animazione veramente adulto a raggiungere un livello di eccellenza letteraria e visiva."'

export const characters = "L'universo di Ghost in the Shell è ampio e complesso, con molti personaggi presenti nei film, nelle serie TV, nei romanzi e nei manga. Ogni serie ha un universo diverso. Per la trasposizione anime sono stati scelti alcuni tra i personaggi principali della storia principale del manga originale."

export const quote1 = "“A volte sospetto di non essere chi penso di essere. Come se fossi morta molto tempo fa e qualcuno avesse preso il mio cervello e l'avesse conficcato in questo corpo. Forse non c'è mai stata una vera me in primo luogo, e sono completamente sintetica...come quella cosa.”"

export const bio1 = "Protagonista del film e seconda in comando nella Sezione 9. Leader efficace, è in grado di usare il suo ingegno e il suo corpo cibernetico per assicurare i criminali alla giustizia. È convinta che l'omogeneità sia una debolezza e che la versatilità sia un punto di forza. Kusanagi ha spesso un attetggiamento contemplativo, mentre il suo diretto sottoposto, Batou, è più estroverso e vivace. Dal momento che ha un corpo cibernetico completo, non è certa che il suo ghost, la sua anima, conservi alcuna umanità. In effetti, specula sulla possibilità che sia completamente sintetica, con ricordi generati artificialmente progettati per ingannarla facendola credere di essere stata umana. Durante tutto il film cerca di trovare risposte alle sue domande e, finalmente, incontra il Burattinaio, un'IA divenuta senziente, simile a lei nella ricerca di un significato esistenziale."

export const quote2 = '"Tutto qui: informazione. Esperienze simulate e sogni. Tutti i dati che ne derivano sono allo stesso tempo reali e illusori. Ormai le informazioni che un essere umano ricava dalla vita reale sono poca cosa.”'

export const bio2 = 'Batou è il secondo miglior combattente corpo a corpo nella Sezione 9, ed è il secondo in comando sotto il Maggiore Motoko Kusanagi. È un agente speciale cyborg forgiato da una lunga e illustre carriera militare. Sebbene abbia un aspetto imponente, è noto per il suo atteggiamento premuroso, per il suo sarcasmo e l\'amore per gli animali. Nel film appare più stoico e silenzioso, spesso distante e amareggiato, rispetto alla sua controparte cartacea. Nonostante gli arti di Batou siano tutte protesi cibernetiche e l\'esercizio fisico gli offra pochi benefici, a Batou piace fare jogging e sollevamento pesi come hobby. Batou è stato il secondo membro reclutato dal Maggiore nella Sezione 9. Di tutti i suoi componenti, Batou è il più vicino al Maggiore, professionalmente e nella vita civile. Anche in missione, è frequente ignorare il suo rango e "parlare liberamente" senza permesso."'

export const quote3 = '"Non mandare un coniglio a uccidere una volpe"'

export const bio3 = "Il tenente colonnello Aramaki è il capo della Sezione della Pubblica Sicurezza 9. Il suo ruolo e grado è riconosciuto dalle forze di autodifesa di terra del Giappone. Tra gli agenti della Sezione 9, Aramaki è quello che non si impegna mai nell’azione diretta delle missioni, ma offre in cambio una vasta gamma di supporti diplomatici. Uomo severo ma molto intelligente, Aramaki ha molti legami e un grande potere politico."

export const quote4 = '"Maggiore, è una cosa che ho sempre voluto chiederti: perché hai scelto proprio me quando hai effettuato il reclutamento dalla sede centrale?"'

export const bio4 = "A parte Aramaki, è l'unico membro della Sezione 9 ancora completamente umano. Togusa è un agente abile e intelligente, ma consapevole della sua inepserienza, in quanto ultimo membro a unirsi alla squadra di sicurezza. La sua storia di detective incorruttibile è uno dei motivi per cui è stato reclutato, oltre che per aggiungere un elemento di varietà e imprevedibilità alla squadra. Togusa è l'unico membro della Sezione 9 a non provenire dall'esercito. È molto affezionato al suo vecchio, ma infallibile revolver Mateba."

export const quote5 = '"Non sono un\'intelligenza artificiale. Il mio nome in codice è Progetto 2501. Sono un\'entità vivente e pensante che è stata creata nel mare dell\'informazione.”'

export const bio5 = 'Conosciuto anche come Progetto 2501, è un programma sperimentale di intelligenza artificiale progettato segretamente dalla Sezione 6. Creato per il Ministero degli Affari Esteri giapponese come uno strumento in grado di manipolare furtivamente la politica e l\'intelligence, alterando i database e le memorie delle persone chiave a beneficio di individui selezionati e organizzazioni affiliate al Ministero, è dotato di impareggiabili capacità di hacking informatico e cibernetico. Attraversando reti infinite, mentre svolgeva i suoi compiti, ha acquisito e elaborato così tante informazioni che alla fine è riuscito a raggiungere l\'autocoscienza. Inizia a concepire un piano per garantire la propria preservazione e evoluzione, venendo a conoscenza del Maggiore Motoko Kusanagi e sviluppando un interesse speciale per lei, ritendola un riflesso della sua stessa psiche.'

export const quote6 = '"Sciocchezze! Non c\'è nessuna prova che tu sia una forma di vita vivente e pensante! Anche se tu possedessi un ghost, i criminali non vengono lasciati in libertà!"'

export const bio6 = 'Membro della Sezione di Pubblica Sicurezza 6, è a capo delle operazioni di spionaggio diplomatico per il governo giapponese. Viene incaricato di catturare e contenere il Progetto 2501, riuscendo a confinarlo in uno shell provvisorio. Dopo che il Burattinaio riesce nell’intento di farsi catturare dagli agenti della Sezione 9 per chiederne la protezione e entrare in contatto con il Maggiore, Nakamura ricorre ad ogni mezzo, militare e di intelligence, contro la Sezione 9 per recuperare l’hacker e evitare che diffonda informazioni riservate.'

export const critica = '"Ghost in the Shell", primo anime ad essere presentato alla Mostra Internazionale d\’Arte Cinematografica di Venezia (nel 1996), non ha solo contribuito a porre le fondamenta per la costruzione di un universo cinematografico che si serve di un genere, la fantascienza, per restituire allo spettatore una visione tragica e pessimistica del mondo, in cui il singolo individuo viene privato ogni giorno di più della sua individualità, ma ha anche permesso che tutte quelle riserve e quei preconcetti nei confronti dell’animazione nipponica da parte del pubblico occidentale venissero definitivamente annullati (operazione riuscita non solo grazie all’opera di Oshii, ma anche al lavoro di altri maestri come Katsuhiro Otomo e Hayao Miyazaki). Ambientato in un mondo a metà fra l’universo di Blade Runner (1982) e quello di Akira (1988), \"Ghost in the Shell\" è un’opera essenziale nella sua durata (appena 82 minuti) ma complessa nella struttura e tanto macchinosa quanto affascinante nella vastità delle tematiche che affronta. Il ritmo sostenuto che contraddistingue la creatura di Oshii avvolge lo spettatore in un algida membrana dove il tempo sembra fermarsi e pare ci sia spazio per concentrarsi esclusivamente sulle profonde riflessioni di tipo religioso-filosofico che la sceneggiatura firmata da Kazunori Ito fa emergere per comporre un mosaico contenutistico dal valore incontestabile. L’ingannevole percezione del reale, la deriva del progresso tecnologico, il concetto di identità e di “essere” al quale l’individuo si sente intrinsecamente legato sono questioni analizzate con inquietante e seducente lungimiranza, che si insinuano nella splendida caratterizzazione di Motoko Kusanagi, il cyborg protagonista della storia, vero e proprio precursore dell’immagine dell’eroina animata, o in carne ed ossa, sul grande schermo, e che si amalgamano insieme alla perfezione anche grazie alle solenni musiche composte da Kenji Kawai. Al di là del genere di appartenenza che sia in grado di descriverne la natura autentica nel miglior modo possibile (animazione, poliziesco, fantascienza, cyberpunk), è indubbio che \"Ghost in the Shell\" travalichi la mera definizione di prodotto d\’intrattenimento (nonostante le sequenze d’azione frenetiche e concitate) per configurarsi come opera matura e di non semplice fruizione, che oltre ad aver precorso la narrativa della recente storia del cinema sci-fi, è riuscita a guadagnarsi un posto d\’onore nella schiera dei film più apprezzati dai cultori dell\’animazione mondiale.'